name: Build documentation

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.DOC_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "bugelniels@gmail.com"
          git config --global user.name "BugelNiels"

      - name: Checkout base repository
        uses: actions/checkout@v3

      - name: Set up Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Initialize and update doxygen-awesome-css
        run: |
          git submodule update --init --recursive external/doxygen-awesome-css

      - name: Generate documentation
        run: |
          project_version=$(head -n 1 version.txt)
          ( cat docs/Doxyfile ; echo "PROJECT_NUMBER = $project_version" ) | doxygen -

      - name: Copy documentation
        run: |
          mkdir -p ${{ runner.temp }}/docs
          cp -r docs/html/* ${{ runner.temp }}/docs/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Update gh-pages content
        run: |
          # Remove existing page content
          rm -rf ./* 
          cp -r ${{ runner.temp }}/docs/* .

      - name: Push changes
        run: |
          git add .
          git commit -m "Updated documentation"
          git push origin gh-pages